// @ts-ignore - vi is available in test environment
export const captureException = vi.fn()
