export const captureException = jest.fn()
